use fields instead of __match_args__
openvinotoolkit/openvino_tokenizers pull request #286
Opened 2024-10-11 13:59 UTC by pavel-esir

Follow up for CVS-146675. Python <= 3.9 does not have __match_args__, use fields instead.

2024-10-11 14:08 UTC, apaniukov approved these changes

2024-10-11 17:38 UTC, andrei-kochin requested changes

2024-10-11 17:38 UTC, andrei-kochin commented on python/openvino_tokenizers/utils.py
>          v = getattr(params, key)
```suggestion
        v = getattr(params, key.name)
```

2024-10-11 17:38 UTC, andrei-kochin commented on tests/tokenizers_test.py
>              val = getattr(conversion_params, key)
```suggestion
            val = getattr(conversion_params, key.name)
```

2024-10-11 18:05 UTC, andrei-kochin commented on python/openvino_tokenizers/convert_tokenizer.py
>                  if kwargs.get(key) is not None:
```suggestion
                if kwargs.get(key.name) is not None:
```

2024-10-11 18:16 UTC, andrei-kochin commented on python/openvino_tokenizers/utils.py
>          ov_tokenizer.set_rt_info(v, key)
```suggestion
        ov_tokenizer.set_rt_info(v, key.name)
```

2024-10-12 06:03 UTC, andrei-kochin approved these changes

2024-10-12 06:04 UTC, merged