Add String Mapping Op
openvinotoolkit/openvino_tokenizers pull request #42
Opened 2024-02-27 11:41 UTC by apaniukov

2024-02-29 12:59 UTC, rkazants commented on python/openvino_tokenizers/tokenizer_pipeline.py
> -
do we need to remove it? please check

2024-02-29 13:00 UTC, apaniukov commented on python/openvino_tokenizers/tokenizer_pipeline.py
> -
Yes, but not necessary in this PR.

2024-03-01 09:36 UTC, rkazants commented on src/vocab_encoder.cpp
> +        auto packed_vocab_const = as_type_ptr<Constant>(arguments[3].get_node_shared_ptr()->get_input_node_shared_ptr(0));
please fix this to use unpacked string tensor format for vocab

2024-03-01 09:37 UTC, rkazants commented on src/vocab_encoder.cpp
> +        auto packed_vocab_const = as_type_ptr<Constant>(arguments[3].get_node_shared_ptr()->get_input_node_shared_ptr(0));
Also, this input may be not necessarily  of Constant type

2024-03-01 09:37 UTC, rkazants commented on src/vocab_encoder.cpp
> +    this->set_output_type(0, element::i32, get_input_partial_shape(0));
Please support `i64` type for values

2024-03-01 09:38 UTC, rkazants requested changes
Now it is not suitable for TensorFlow needs:
1. format of vocal keys needs to be changed
2. need support of i64 values

2024-03-01 11:10 UTC, rkazants approved these changes

2024-03-01 11:35 UTC, merged